name: Crawl CTB Data
on:
  schedule:
    - cron: "3 21 * * *" # 05:03 (HKT) daily, as API update at 0500am daily
  workflow_dispatch:

jobs:
  Crawl-CTB-Data:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    env:
      AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v7

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python environment
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'
          architecture: 'x64'
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install

      - name: Crawl CTB raw data
        env:
          REQUEST_LIMIT: "6"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: poetry run python ./crawling/ctb_crawl.py --force

      - name: Upload CTB raw data to S3
        run: |
          aws s3 cp data/ctb.raw.routeList.json s3://${{ secrets.AWS_S3_BUCKET }}/transport/ctb/ctb.raw.routeList.json
          aws s3 cp data/ctb.raw.routeStopList.json s3://${{ secrets.AWS_S3_BUCKET }}/transport/ctb/ctb.raw.routeStopList.json
          aws s3 cp data/ctb.raw.stopList.json s3://${{ secrets.AWS_S3_BUCKET }}/transport/ctb/ctb.raw.stopList.json

      - name: Archive CTB raw data
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: CTB Raw Files
          retention-days: 14
          path: |
            data/ctb.raw.routeList.json
            data/ctb.raw.routeStopList.json
            data/ctb.raw.stopList.json
