name: Data Fetching
on:
  push:
      # branches-ignore:
      #   - alpha
    branches:
      - master
  pull_request:
  schedule:
    - cron: "10 9,21 * * *" # 05:10 and 17:10 (HKT) daily
  workflow_dispatch:

jobs:
  Fetch-Route-Data:
    if: ${{ github.event_name != 'pull_request' || github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write

    env:
      ALPHA_BRANCH_NAME: alpha
      AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Check if alpha branch status
        id: alpha-check
        shell: bash
        run: |
          set -o xtrace
          if git rev-parse --verify --no-revs "origin/${ALPHA_BRANCH_NAME}" && ! git diff --exit-code --merge-base origin/master "origin/${ALPHA_BRANCH_NAME}" --
          then
            echo "alpha_newer=yes" >> "$GITHUB_OUTPUT"
          fi

      - name: Set github page upload path by alpha branch status
        id: target-path
        shell: bash
        run: |
          set -o xtrace
          should_deploy_to_alpha=${{ steps.alpha-check.outputs.alpha_newer == 'yes' && github.ref_name == env.ALPHA_BRANCH_NAME }}
          if [ "${should_deploy_to_alpha}" == "true" ]
          then
            echo "target-path=alpha/" >> "$GITHUB_OUTPUT"
          else
            echo "target-path=/" >> "$GITHUB_OUTPUT"
          fi

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python environment
        uses: actions/setup-python@v7
        with:
            python-version: '3.14'
            architecture: 'x64'
            cache: 'poetry'

      - name: Install dependencies
        run: poetry install

      - name: Download GMB raw data from S3
        continue-on-error: true
        run: |
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }}/transport/gmb/gmb.raw.routeNoList.json data/ || true
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }}/transport/gmb/gmb.raw.routeList.json data/ || true
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }}/transport/gmb/gmb.raw.routeStopList.json data/ || true
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }}/transport/gmb/gmb.raw.stopList.json data/ || true

      - name: Download CTB raw data from S3
        continue-on-error: true
        run: |
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }}/transport/ctb/ctb.raw.routeList.json data/ || true
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }}/transport/ctb/ctb.raw.routeStopList.json data/ || true
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }}/transport/ctb/ctb.raw.stopList.json data/ || true

      - name: Download NLB raw data from S3
        continue-on-error: true
        run: |
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }}/transport/nlb/nlb.raw.routeList.json data/ || true
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }}/transport/nlb/nlb.raw.routeStopList.json data/ || true
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }}/transport/nlb/nlb.raw.stopList.json data/ || true

      - name: Crawling resources
        timeout-minutes: 5
        shell: bash
        env:
          REQUEST_LIMIT: "6"
        run: |
          set -o xtrace
          poetry run python ./crawling/parseJourneyTime.py
          poetry run python ./crawling/parseGtfs.py
          poetry run python ./crawling/parseHoliday.py
          poetry run python ./crawling/ctb_crawl.py
          poetry run python ./crawling/ctb.py
          poetry run python ./crawling/kmb_crawl.py
          poetry run python ./crawling/kmb.py
          poetry run python ./crawling/nlb_crawl.py
          poetry run python ./crawling/nlb.py
          poetry run python ./crawling/lrtfeeder.py
          poetry run python ./crawling/lightRail.py
          poetry run python ./crawling/mtr.py
          poetry run python ./crawling/gmb_crawl.py
          poetry run python ./crawling/gmb.py
          poetry run python ./crawling/sunferry.py
          poetry run python ./crawling/fortuneferry.py
          poetry run python ./crawling/hkkf.py
          poetry run python ./crawling/matchGtfs.py
          poetry run python ./crawling/cleansing.py
          poetry run python ./crawling/mergeRoutes.py
          poetry run python ./crawling/mergeStopList.py
          poetry run python ./crawling/routeCompare.py
          poetry run python ./crawling/mtrExits.py

      - name: Upload integrated data to S3
        run: |
          aws s3 cp data/holidays.json s3://${{ secrets.AWS_S3_BUCKET }}/transport/integrated/holidays.json
          aws s3 cp data/gtfs.json s3://${{ secrets.AWS_S3_BUCKET }}/transport/integrated/gtfs.json
          aws s3 cp data/nearby_operators_stops.json s3://${{ secrets.AWS_S3_BUCKET }}/transport/integrated/nearby_operators_stops.json
          aws s3 cp data/operators_stops.json s3://${{ secrets.AWS_S3_BUCKET }}/transport/integrated/operators_stops.json
          aws s3 cp data/service_days.json s3://${{ secrets.AWS_S3_BUCKET }}/transport/integrated/service_days.json
          aws s3 cp data/operators_routes.json s3://${{ secrets.AWS_S3_BUCKET }}/transport/integrated/operators_routes.json
          aws s3 cp data/integrated_routes.json s3://${{ secrets.AWS_S3_BUCKET }}/transport/integrated/integrated_routes.json
          aws s3 cp data/gtfs_operators_stops_map.json s3://${{ secrets.AWS_S3_BUCKET }}/transport/integrated/gtfs_operators_stops_map.json

      - name: Archive crawling outputs
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: Crawled Files
          retention-days: 14
          path: |
            data/holidays.json
            data/integrated_routes.json
            data/operators_routes.json
            data/service_days.json
            data/operators_stops.json
            data/nearby_operators_stops.json
            data/routeFareList*
            data/routeList*
            data/stopCandidates*
            data/stopList*
            data/stopMap*
            data/routeTime.json
            data/gtfs-tc
            data/gtfs.json
            data/gtfs_operators_stops_map.json
            data/routeGtfs*
            data/gtfs-tc.zip
            data/ROUTE_BUS.xml
            data/route-ts/
            data/exits.mtr.json
            data/0versions.json
      - name: create deployment folder
        shell: bash
        run: mkdir -p build
      - name: cp files into deployment folder
        shell: bash
        run: |
          cp \
          data/holidays.json \
          data/integrated_routes.json \
          data/operators_routes.json \
          data/service_days.json \
          data/operators_stops.json \
          data/nearby_operators_stops.json \
          CNAME \
          data/exits.mtr.json \
          data/gtfs_operators_stops_map.json \
          data/0versions.json \
          build/
      - name: cp route-ts into deployment folder
        shell: bash
        run: cp -r data/route-ts build

      - name: Copy master build to alpha when no update or not exist
        if: github.ref_name == 'master' && steps.alpha-check.outputs.alpha_newer != 'yes'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            target-folder: alpha/
            folder: build
            commit-message: "Update resources from ${{ github.run_number }}:${{ github.run_attempt }}"
            branch: gh-pages
            clean: false
            clean-exclude: |
              alpha/*
      
      - name: Update resources
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            target-folder: ${{ steps.target-path.outputs.target-path }}
            folder: build
            commit-message: "Update resources from ${{ github.run_number }}:${{ github.run_attempt }}"
            branch: gh-pages
            clean: false
            clean-exclude: |
              alpha/*

      - name: Trigger alpha build on schedule
        if: ( github.event_name == 'schedule' || github.event_name=='workflow_dispatch') && steps.alpha-check.outputs.alpha_newer == 'yes'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: ${{ github.workflow }}
          ref: ${{ env.ALPHA_BRANCH_NAME }}
